---
# file: tasks/installation.yml
#
# installation tasks.
#
- name: 'Install Python PIP'
  tags: 'aws-cli'
  become: 'yes'
  apt: >
    pkg=python-pip
    state=latest

- name: installation | ensure awscli is installed
  pip:
    name=awscli
    version="{{ awscli_version }}"
#  become: yes
