---  
- name: Create Active Directory user 
  ldap_entry: 
    dn: CN=Martin St-Pierre 2,OU=Lab Users,OU=activedirectory,DC=activedirectory,DC=pocquebec,DC=org
    objectClass:
      - person
    attributes:
      sn: St-Pierre2
    state: present
    server_uri: ldap://activedirectory.pocquebec.org
    bind_dn: CN=Ansible Tower,OU=Users,OU=activedirectory,DC=activedirectory,DC=pocquebec,DC=org
    bind_pw: '{{ ldap_password }}'
    validate_certs: no
  register: credentials
- debug: var=credentials
  ldap_attr:
    dn: CN=Martin St-Pierre 2,OU=Lab Users,OU=activedirectory,DC=activedirectory,DC=pocquebec,DC=org
    name: displayName
    values: Martin St-Pierre 2
    state: exact