---  
- name: Create Active Directory user 
  ldap_entry: 
    dn: cn=Martin St-Pierre 2,ou=Users,dc=activedirectory,dc=pocquebec,dc=org
    objectClass:
      - person
    attributes:
      sn: St-Pierre2
    state: present
    server_uri: ldap://activedirectory.pocquebec.org
    bind_dn: cn=Ansible Tower,dc=activedirectory,dc=pocquebec,dc=org
    bind_pw: '{{ ldap_password }}'
    validate_certs: no
  register: credentials
- debug: var=credentials