---  
- name: Create Active Directory user 
  ldap_entry: 
    dn: 'CN={{ first_name }} {{ last_name }},OU=Lab Users,OU=activedirectory,DC=activedirectory,DC=pocquebec,DC=org'
    objectClass:
      - top
      - person
      - organizationalPerson
      - user
    attributes:
      sn: '{{ last_name }}'
      displayName: '{{ first_name }} {{ last_name }}'
      distinguishedName: 'CN={{ first_name }} {{ last_name }},OU=Lab Users,OU=activedirectory,DC=activedirectory,DC=pocquebec,DC=org'
      givenName: '{{ first_name }}'
      mail: martin.st-pierre3@sct.gouv.qc.ca
      sAMAccountName: '{{ username }}'
      userPrincipalName: '{{ username }}@activedirectory.pocquebec.org'
    state: present
    server_uri: ldaps://activedirectory.pocquebec.org
    bind_dn: CN=Ansible Tower,OU=Users,OU=activedirectory,DC=activedirectory,DC=pocquebec,DC=org
    bind_pw: '{{ ldap_password }}'
    validate_certs: no
  register: credentials
- debug: var=credentials
- name: Add attribut 
  ldap_attr:
    dn: CN=AWS Delegated Administrators,OU=AWS Delegated Groups,DC=activedirectory,DC=pocquebec,DC=org
    name: "{{ item.key }}"
    values: "{{ item.value }}"
    state: present
    server_uri: ldaps://activedirectory.pocquebec.org
    bind_dn: CN=Ansible Tower,OU=Users,OU=activedirectory,DC=activedirectory,DC=pocquebec,DC=org
    bind_pw: '{{ ldap_password }}'
    validate_certs: no
  with_dict:
    member: 'CN={{ first_name }} {{ last_name }},OU=Lab Users,OU=activedirectory,DC=activedirectory,DC=pocquebec,DC=org'
