---   
- name: Invite GitHub user to join CQEN 
  uri:
    url: "https://api.github.com/orgs/CQEN-QDCE/memberships/stpma02"
    url_username: '{{ ghba_username }}'
    url_password: '{{ ghba_password }}'
    force_basic_auth: yes