---
- name: "Start all workers node"
  gather_facts: no
  hosts: localhost
  tasks:
    - name: "Get instances"
      ec2_instance_facts:
        region: "{{ region }}"
      register: instances

    - name: "Extract the list of instance ID"
      set_fact:
        instance_ids: "{{ instances.instances | map(attribute='instance_id') | list }}"

    - debug:
        msg:
          - "The following instances will be started: "
          - "{{ instance_ids }}"

    - name: "Starting instances"
      ec2:
        region: "{{ region }}"
        instance_ids: "{{ instance_ids }}"
        state: running
