---
- name: "Turn on workers node that have the 'bootup' tag set to yes."
  gather_facts: no
  hosts: localhost
  tasks:
    - name: "Get all instances"
      ec2_instance_facts:
        region: "{{ region }}"
      register: all_instances

    - name: "Get instances with a tag bootup=yes"
      ec2_instance_facts:
        region: "{{ region }}"
        filters:
          "tag:bootup": "yes"
      register: bootup_instances

    - name: "Extract the list of bootup instance ID"
      set_fact:
        instance_ids: "{{ bootup_instances.instances | map(attribute='instance_id') | list }}"

    - debug:
        msg:
          - "The following instances will be opened: "
          - "{{ instance_ids }}"

#    - name: "Turn on instances"
#      ec2:
#        region: "{{ region }}"
#        instance_ids: "{{ instance_ids }}"
#        state: running
