---
- name: "Start workers node that have the 'shutdown' tag set to yes."
  gather_facts: no
  hosts: localhost
  tasks:
    - name: "Get instances with a tag shutdown=yes"
      ec2_instance_facts:
        region: "{{ region }}"
        filters:
          "tag:shutdown": "yes"
      register: instances

    - name: "Extract the list of instance ID"
      set_fact:
        instance_ids: "{{ instances.instances | map(attribute='instance_id') | list }}"

    - debug:
        msg:
          - "The following instances will be started: "
          - "{{ instance_ids }}"

    - name: "Starting instances"
      ec2:
        region: "{{ region }}"
        instance_ids: "{{ instance_ids }}"
        state: running
